/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ExampleFastifyRedis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "ExampleFastifyService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ExampleFastifyVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
